version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    container_name: "blog-container"
    volumes:
      - .:/application
    expose:
      - 8000
    env_file:
      - .env
    networks:
      - app
    depends_on:
      - db


  db:
    container_name: "database-blog-container"
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog_base
      - MYSQL_USER=viktor
      - MYSQL_PASSWORD=14051998
    ports:
      - "5566:3306"
    networks:
      - app
    security_opt:
        - seccomp:unconfined

  nginx:
    build: ./docker/nginx
    container_name: "flask_nginx"
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - app
    volumes:
      - .:/application

networks:
  app:
    driver: bridge
